name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            filename: metrics.plugin.lines.svg
            user: swat-sccs
            token: ${{ secrets.METRICS_TOKEN }}
            base: repositories
            plugin_lines: yes
            plugin_lines_sections: [base, repositories, history]
            plugin_lines_history_limit: 4
